### PR TITLE
Initial commit of app and updated readme

### PR DESCRIPTION
**Pull request by thaumos**

### CODE REVIEW

**Comment by thaumos** [comment]
@cchurch , could you bless this?

**Comment by cchurch** [comment]
I would lean against vendoring the requests and splunklib dependencies in our own repo, but rather including those at build time.

I've got a `build.xml` that downloads those and creates a zip of the app here: https://github.com/cchurch/ansible-tower-splunk-framework/blob/tower_app/build.xml (based on https://github.com/damiendallimore/SplunkModularInputsPythonFramework/blob/master/build/build.xml).

**Comment by thaumos** [comment]
great, love it!  I'll fix this and get it updated.

**Comment by thaumos** [comment]
@cchurch, updated my PR. Care to take a look?

**Comment by cchurch** [comment]
:+1:  I'll add in my build.xml once merged (though ant makes me want to 👊 a 👶, it works for now).

**Comment by thaumos** [comment]
alright @cchurch, it's been merged.

**Pull request merged**
